import { ISmartphone, IProduct } from './../types/types';
import id0 from './../img/redmi-note-11s.jpg';
import id1 from './../img/redmi-note-10s.jpg';
import id2 from './../img/iphone13.jpg';
import id3 from './../img/galaxyA52.jpg';
import id4 from './../img/iphone11.jpg';
import id5 from './../img/redmi-9a.jpg';
import id6 from './../img/honor-x9.jpg';
import id7 from './../img/huawei-y70.jpg';
import id8 from './../img/zte-blade-a31.jpg';
import id9 from './../img/zte-blade-a51.jpg';
import id10 from './../img/poco-x3-pro.jpg';
import id11 from './../img/iphone12.jpg';
import id12 from './../img/iphone13pro.jpg';
import id13 from './../img/redmi-note-10pro.jpg';
import id14 from './../img/xiaomi-11-lite.jpg';
import id15 from './../img/galaxyS21.jpg';
import id16 from './../img/galaxyA12.jpg';
import id17 from './../img/redmi-9t.jpg';
import id18 from './../img/realme8.jpg';
import id19 from './../img/galaxyM12.jpg';
import id20 from './../img/galaxyS20.jpg';
import id21 from './../img/iphone-se.jpg';
import id22 from './../img/galaxyM32.jpg';
import id23 from './../img/mi11-lite.jpg';
import id24 from './../img/iphone12mini.jpg';
import id25 from './../img/poco-f3.jpg';
import id26 from './../img/honor50.jpg';
import id27 from './../img/redmi-note-8.jpg';
import id28 from './../img/iphone-xr.jpg';
import id29 from './../img/poco-m4-pro.jpg';

export type Data = {
  products: ISmartphone[] | IProduct[];
};

const data: Data = {
  products: [
    {
      id: 0,
      brand: 'Xiaomi',
      type: 'Smartphone',
      name: 'Redmi Note 11s',
      color: 'Grey',
      year: 2022,
      quantity: 12,
      price: 349.99,
      numberOfCameras: 4,
      RAM: '6GB',
      memory: '128GB',
      imgSrc: id0,
      isPopular: true,
    },
    {
      id: 1,
      brand: 'Xiaomi',
      type: 'Smartphone',
      name: 'Redmi Note 10s',
      color: 'Onyx',
      year: 2021,
      quantity: 30,
      price: 229.99,
      numberOfCameras: 4,
      RAM: '6GB',
      memory: '128GB',
      imgSrc: id1,
      isPopular: false,
    },
    {
      id: 2,
      brand: 'Apple',
      type: 'Smartphone',
      name: 'iPhone 13',
      color: 'Dark Night',
      year: 2021,
      quantity: 10,
      price: 999.99,
      numberOfCameras: 2,
      RAM: '4GB',
      memory: '128GB',
      imgSrc: id2,
      isPopular: true,
    },
    {
      id: 3,
      brand: 'Samsung',
      type: 'Smartphone',
      name: 'Galaxy A52 SM-A525F/DS',
      color: 'Black',
      year: 2021,
      quantity: 0,
      price: 299.99,
      numberOfCameras: 4,
      RAM: '4GB',
      memory: '128GB',
      imgSrc: id3,
      isPopular: true,
    },
    {
      id: 4,
      brand: 'Apple',
      type: 'Smartphone',
      name: 'iPhone 11',
      color: 'Black',
      year: 2019,
      quantity: 3,
      price: 549.99,
      numberOfCameras: 2,
      RAM: '4GB',
      memory: '64GB',
      imgSrc: id4,
      isPopular: false,
    },
    {
      id: 5,
      brand: 'Xiaomi',
      type: 'Smartphone',
      name: 'Redmi 9A',
      color: 'Grey',
      year: 2020,
      quantity: 30,
      price: 129.99,
      numberOfCameras: 1,
      RAM: '2GB',
      memory: '32GB',
      imgSrc: id5,
      isPopular: false,
    },
    {
      id: 6,
      brand: 'HONOR',
      type: 'Smartphone',
      name: 'X9',
      color: 'Silver',
      year: 2022,
      quantity: 25,
      price: 339.99,
      numberOfCameras: 4,
      RAM: '6GB',
      memory: '128GB',
      imgSrc: id6,
      isPopular: true,
    },
    {
      id: 7,
      brand: 'Huawei',
      type: 'Smartphone',
      name: 'nova Y70',
      color: 'Blue',
      year: 2022,
      quantity: 0,
      price: 199.99,
      numberOfCameras: 3,
      RAM: '4GB',
      memory: '128GB',
      imgSrc: id7,
      isPopular: true,
    },
    {
      id: 8,
      brand: 'ZTE',
      type: 'Smartphone',
      name: 'Blade A31 NFC',
      color: 'Grey',
      year: 2021,
      quantity: 50,
      price: 99.99,
      numberOfCameras: 1,
      RAM: '2GB',
      memory: '32GB',
      imgSrc: id8,
      isPopular: false,
    },
    {
      id: 9,
      brand: 'ZTE',
      type: 'Smartphone',
      name: 'Blade A51 NFC',
      color: 'Blue',
      year: 2021,
      quantity: 0,
      price: 129.99,
      numberOfCameras: 2,
      RAM: '2GB',
      memory: '64GB',
      imgSrc: id9,
      isPopular: false,
    },
    {
      id: 10,
      brand: 'POCO',
      type: 'Smartphone',
      name: 'X3 Pro',
      color: 'Black',
      year: 2021,
      quantity: 31,
      price: 599.99,
      numberOfCameras: 4,
      RAM: '8GB',
      memory: '256GB',
      imgSrc: id10,
      isPopular: true,
    },
    {
      id: 11,
      brand: 'Apple',
      type: 'Smartphone',
      name: 'iPhone 12',
      color: 'Black',
      year: 2020,
      quantity: 15,
      price: 999.99,
      numberOfCameras: 2,
      RAM: '4GB',
      memory: '128GB',
      imgSrc: id11,
      isPopular: true,
    },
    {
      id: 12,
      brand: 'Apple',
      type: 'Smartphone',
      name: 'iPhone 13 Pro',
      color: 'Silver',
      year: 2021,
      quantity: 24,
      price: 129.99,
      numberOfCameras: 3,
      RAM: '6GB',
      memory: '128GB',
      imgSrc: id12,
      isPopular: true,
    },
    {
      id: 13,
      brand: 'Xiaomi',
      type: 'Smartphone',
      name: 'Redmi Note 10 Pro',
      color: 'Grey',
      year: 2021,
      quantity: 0,
      price: 349.99,
      numberOfCameras: 4,
      RAM: '8GB',
      memory: '128GB',
      imgSrc: id13,
      isPopular: true,
    },
    {
      id: 14,
      brand: 'Xiaomi',
      type: 'Smartphone',
      name: '11 Lite 5G NE',
      color: 'Black',
      year: 2021,
      quantity: 30,
      price: 399.99,
      numberOfCameras: 3,
      RAM: '8GB',
      memory: '128GB',
      imgSrc: id14,
      isPopular: true,
    },
    {
      id: 15,
      brand: 'Samsung',
      type: 'Smartphone',
      name: 'Galaxy S21 5G',
      color: 'White',
      year: 2021,
      quantity: 5,
      price: 899.99,
      numberOfCameras: 3,
      RAM: '8GB',
      memory: '256GB',
      imgSrc: id15,
      isPopular: true,
    },
    {
      id: 16,
      brand: 'Samsung',
      type: 'Smartphone',
      name: 'Galaxy A12',
      color: 'Black',
      year: 2021,
      quantity: 0,
      price: 229.99,
      numberOfCameras: 4,
      RAM: '4GB',
      memory: '64GB',
      imgSrc: id16,
      isPopular: false,
    },
    {
      id: 17,
      brand: 'Xiaomi',
      type: 'Smartphone',
      name: 'Redmi 9T',
      color: 'Grey',
      year: 2021,
      quantity: 10,
      price: 249.99,
      numberOfCameras: 4,
      RAM: '4GB',
      memory: '128GB',
      imgSrc: id17,
      isPopular: false,
    },
    {
      id: 18,
      brand: 'Realme',
      type: 'Smartphone',
      name: '8',
      color: 'Silver',
      year: 2021,
      quantity: 37,
      price: 299.99,
      numberOfCameras: 4,
      RAM: '6GB',
      memory: '128GB',
      imgSrc: id18,
      isPopular: true,
    },
    {
      id: 19,
      brand: 'Samsung',
      type: 'Smartphone',
      name: 'Galaxy M12 SM-M127F/DSN',
      color: 'Black',
      year: 2021,
      quantity: 35,
      price: 229.99,
      numberOfCameras: 4,
      RAM: '3GB',
      memory: '32GB',
      imgSrc: id19,
      isPopular: false,
    },
    {
      id: 20,
      brand: 'Samsung',
      type: 'Smartphone',
      name: 'Galaxy S20 FE SM-G780G',
      color: 'Blue',
      year: 2020,
      quantity: 5,
      price: 449.99,
      numberOfCameras: 3,
      RAM: '6GB',
      memory: '128GB',
      imgSrc: id20,
      isPopular: false,
    },
    {
      id: 21,
      brand: 'Apple',
      type: 'Smartphone',
      name: 'iPhone SE',
      color: 'Black',
      year: 2020,
      quantity: 10,
      price: 549.99,
      numberOfCameras: 1,
      RAM: '3GB',
      memory: '64GB',
      imgSrc: id21,
      isPopular: true,
    },
    {
      id: 22,
      brand: 'Samsung',
      type: 'Smartphone',
      name: 'Galaxy M32',
      color: 'Black',
      year: 2021,
      quantity: 20,
      price: 389.99,
      numberOfCameras: 4,
      RAM: '6GB',
      memory: '128GB',
      imgSrc: id22,
      isPopular: false,
    },
    {
      id: 23,
      brand: 'Xiaomi',
      type: 'Smartphone',
      name: 'Mi 11 Lite',
      color: 'Black',
      year: 2021,
      quantity: 15,
      price: 129.99,
      numberOfCameras: 3,
      RAM: '6GB',
      memory: '128GB',
      imgSrc: id23,
      isPopular: true,
    },
    {
      id: 24,
      brand: 'Apple',
      type: 'Smartphone',
      name: 'iPhone 12 mini',
      color: 'Black',
      year: 2021,
      quantity: 12,
      price: 799.99,
      numberOfCameras: 2,
      RAM: '4GB',
      memory: '64GB',
      imgSrc: id24,
      isPopular: false,
    },
    {
      id: 25,
      brand: 'POCO',
      type: 'Smartphone',
      name: 'F3',
      color: 'Black',
      year: 2021,
      quantity: 36,
      price: 449.99,
      numberOfCameras: 3,
      RAM: '8GB',
      memory: '128GB',
      imgSrc: id25,
      isPopular: false,
    },
    {
      id: 26,
      brand: 'HONOR',
      type: 'Smartphone',
      name: '50',
      color: 'Dark Night',
      year: 2021,
      quantity: 21,
      price: 349.99,
      numberOfCameras: 4,
      RAM: '8GB',
      memory: '128GB',
      imgSrc: id26,
      isPopular: true,
    },
    {
      id: 27,
      brand: 'Xiaomi',
      type: 'Smartphone',
      name: 'Redmi Note 8',
      color: 'Blue',
      year: 2021,
      quantity: 0,
      price: 449.99,
      numberOfCameras: 4,
      RAM: '4GB',
      memory: '64GB',
      imgSrc: id27,
      isPopular: false,
    },
    {
      id: 28,
      brand: 'Apple',
      type: 'Smartphone',
      name: 'iPhone XR',
      color: 'Black',
      year: 2018,
      quantity: 0,
      price: 719.99,
      numberOfCameras: 1,
      RAM: '3GB',
      memory: '64GB',
      imgSrc: id28,
      isPopular: false,
    },
    {
      id: 29,
      brand: 'POCO',
      type: 'Smartphone',
      name: 'M4 Pro 5G',
      color: 'Black',
      year: 2021,
      quantity: 18,
      price: 299.99,
      numberOfCameras: 2,
      RAM: '6GB',
      memory: '128GB',
      imgSrc: id29,
      isPopular: true,
    },
  ],
};

export default data;
