import { ISmartphone, IProduct } from './../types/types';
export type Data = {
  products: ISmartphone[] | IProduct[]
}

let data: Data = {
  products: [
    {
      id: 0,
      brand: 'Xiaomi',
      type: 'Smartphone',
      name: 'Redmi Note 11s',
      color: 'Grey',
      year: 2022,
      quantity: 12,
      price: 349.99,
      numberOfCameras: 4,
      RAM: '6GB',
      memory: '128GB',
      imgSrc: 'img/redmi-note-11s.jpg',
      isPopular: true,
    },
    {
      id: 1,
      brand: 'Xiaomi',
      type: 'Smartphone',
      name: 'Redmi Note 10s',
      color: 'Onyx',
      year: 2021,
      quantity: 30,
      price: 229.99,
      numberOfCameras: 4,
      RAM: '6GB',
      memory: '128GB',
      imgSrc: 'img/redmi-note-10s.jpg',
      isPopular: false,
    },
    {
      id: 2,
      brand: 'Apple',
      type: 'Smartphone',
      name: 'IPhone 13',
      color: 'Dark Night',
      year: 2021,
      quantity: 10,
      price: 999.99,
      numberOfCameras: 2,
      RAM: '4GB',
      memory: '128GB',
      imgSrc: 'img/iphone13.jpg',
      isPopular: true,
    },
    {
      id: 3,
      brand: 'Samsung',
      type: 'Smartphone',
      name: 'Galaxy A52 SM-A525F/DS',
      color: 'Black',
      year: 2021,
      quantity: 0,
      price: 299.99,
      numberOfCameras: 4,
      RAM: '4GB',
      memory: '128GB',
      imgSrc: 'img/galaxyA52.jpg',
      isPopular: true,
    },
    {
      id: 4,
      brand: 'Apple',
      type: 'Smartphone',
      name: 'IPhone 11',
      color: 'Black',
      year: 2019,
      quantity: 3,
      price: 549.99,
      numberOfCameras: 2,
      RAM: '4GB',
      memory: '64GB',
      imgSrc: 'img/iphone11.jpg',
      isPopular: false,
    },
    {
      id: 5,
      brand: 'Xiaomi',
      type: 'Smartphone',
      name: 'Redmi 9A',
      color: 'Grey',
      year: 2020,
      quantity: 30,
      price: 129.99,
      numberOfCameras: 1,
      RAM: '2GB',
      memory: '32GB',
      imgSrc: 'img/redmi-9a.jpg',
      isPopular: false,
    },
  ],
}

export default data;